# Generated by Django 5.2.3 on 2025-06-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_rename_birthdey_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='birthdey',
            new_name='birthday',
        ),
    ]
